# pylint: disable=too-many-lines
# pylint: disable=line-too-long

"""Parse luxtronik calculations."""
import logging
from typing import Final, List

from luxtronik.datatypes import (
    LuxtronikDataFieldDefinition,
    LuxtronikDataFieldFactory,
    LuxtronikDataFieldDict,
    BivalenceLevel,
    Bool,
    Celsius,
    Count,
    Energy,
    Errorcode,
    Flow,
    Frequency,
    HeatpumpCode,
    Icon,
    IPAddress,
    Kelvin,
    Level,
    MainMenuStatusLine1,
    MainMenuStatusLine2,
    MainMenuStatusLine3,
    OperationMode,
    Percent2,
    Power,
    Pressure,
    Pulses,
    Seconds,
    SecOperationMode,
    Speed,
    SwitchoffFile,
    Timestamp,
    Unknown,
    Version,
    Voltage,
)

LOGGER = logging.getLogger("Luxtronik.Calculations")

# fmt: off
CALCULATION_DEFINITIONS: Final[List[LuxtronikDataFieldDefinition]] = [
    LuxtronikDataFieldDefinition(0, "Unknown_Calculation_0", Unknown),
    LuxtronikDataFieldDefinition(1, "Unknown_Calculation_1", Unknown),
    LuxtronikDataFieldDefinition(2, "Unknown_Calculation_2", Unknown),
    LuxtronikDataFieldDefinition(3, "Unknown_Calculation_3", Unknown),
    LuxtronikDataFieldDefinition(4, "Unknown_Calculation_4", Unknown),
    LuxtronikDataFieldDefinition(5, "Unknown_Calculation_5", Unknown),
    LuxtronikDataFieldDefinition(6, "Unknown_Calculation_6", Unknown),
    LuxtronikDataFieldDefinition(7, "Unknown_Calculation_7", Unknown),
    LuxtronikDataFieldDefinition(8, "Unknown_Calculation_8", Unknown),
    LuxtronikDataFieldDefinition(9, "Unknown_Calculation_9", Unknown),
    LuxtronikDataFieldDefinition(10, "ID_WEB_Temperatur_TVL", Celsius),
    LuxtronikDataFieldDefinition(11, "ID_WEB_Temperatur_TRL", Celsius),
    LuxtronikDataFieldDefinition(12, "ID_WEB_Sollwert_TRL_HZ", Celsius),
    LuxtronikDataFieldDefinition(13, "ID_WEB_Temperatur_TRL_ext", Celsius),
    LuxtronikDataFieldDefinition(14, "ID_WEB_Temperatur_THG", Celsius),
    LuxtronikDataFieldDefinition(15, "ID_WEB_Temperatur_TA", Celsius),
    LuxtronikDataFieldDefinition(16, "ID_WEB_Mitteltemperatur", Celsius),
    LuxtronikDataFieldDefinition(17, "ID_WEB_Temperatur_TBW", Celsius),
    LuxtronikDataFieldDefinition(18, "ID_WEB_Einst_BWS_akt", Celsius),
    LuxtronikDataFieldDefinition(19, "ID_WEB_Temperatur_TWE", Celsius),
    LuxtronikDataFieldDefinition(20, "ID_WEB_Temperatur_TWA", Celsius),
    LuxtronikDataFieldDefinition(21, "ID_WEB_Temperatur_TFB1", Celsius),
    LuxtronikDataFieldDefinition(22, "ID_WEB_Sollwert_TVL_MK1", Celsius),
    LuxtronikDataFieldDefinition(23, "ID_WEB_Temperatur_RFV", Celsius),
    LuxtronikDataFieldDefinition(24, "ID_WEB_Temperatur_TFB2", Celsius),
    LuxtronikDataFieldDefinition(25, "ID_WEB_Sollwert_TVL_MK2", Celsius),
    LuxtronikDataFieldDefinition(26, "ID_WEB_Temperatur_TSK", Celsius),
    LuxtronikDataFieldDefinition(27, "ID_WEB_Temperatur_TSS", Celsius),
    LuxtronikDataFieldDefinition(28, "ID_WEB_Temperatur_TEE", Celsius),
    LuxtronikDataFieldDefinition(29, "ID_WEB_ASDin", Bool),
    LuxtronikDataFieldDefinition(30, "ID_WEB_BWTin", Bool),
    LuxtronikDataFieldDefinition(31, "ID_WEB_EVUin", Bool),
    LuxtronikDataFieldDefinition(32, "ID_WEB_HDin", Bool),
    LuxtronikDataFieldDefinition(33, "ID_WEB_MOTin", Bool),
    LuxtronikDataFieldDefinition(34, "ID_WEB_NDin", Bool),
    LuxtronikDataFieldDefinition(35, "ID_WEB_PEXin", Bool),
    LuxtronikDataFieldDefinition(36, "ID_WEB_SWTin", Bool),
    LuxtronikDataFieldDefinition(37, "ID_WEB_AVout", Bool),
    LuxtronikDataFieldDefinition(38, "ID_WEB_BUPout", Bool),
    LuxtronikDataFieldDefinition(39, "ID_WEB_HUPout", Bool),
    LuxtronikDataFieldDefinition(40, "ID_WEB_MA1out", Bool),
    LuxtronikDataFieldDefinition(41, "ID_WEB_MZ1out", Bool),
    LuxtronikDataFieldDefinition(42, "ID_WEB_VENout", Bool),
    LuxtronikDataFieldDefinition(43, "ID_WEB_VBOout", Bool),
    LuxtronikDataFieldDefinition(44, "ID_WEB_VD1out", Bool),
    LuxtronikDataFieldDefinition(45, "ID_WEB_VD2out", Bool),
    LuxtronikDataFieldDefinition(46, "ID_WEB_ZIPout", Bool),
    LuxtronikDataFieldDefinition(47, "ID_WEB_ZUPout", Bool),
    LuxtronikDataFieldDefinition(48, "ID_WEB_ZW1out", Bool),
    LuxtronikDataFieldDefinition(49, "ID_WEB_ZW2SSTout", Bool),
    LuxtronikDataFieldDefinition(50, "ID_WEB_ZW3SSTout", Bool),
    LuxtronikDataFieldDefinition(51, "ID_WEB_FP2out", Bool),
    LuxtronikDataFieldDefinition(52, "ID_WEB_SLPout", Bool),
    LuxtronikDataFieldDefinition(53, "ID_WEB_SUPout", Bool),
    LuxtronikDataFieldDefinition(54, "ID_WEB_MZ2out", Bool),
    LuxtronikDataFieldDefinition(55, "ID_WEB_MA2out", Bool),
    LuxtronikDataFieldDefinition(56, "ID_WEB_Zaehler_BetrZeitVD1", Seconds),
    LuxtronikDataFieldDefinition(57, "ID_WEB_Zaehler_BetrZeitImpVD1", Pulses),
    LuxtronikDataFieldDefinition(58, "ID_WEB_Zaehler_BetrZeitVD2", Seconds),
    LuxtronikDataFieldDefinition(59, "ID_WEB_Zaehler_BetrZeitImpVD2", Pulses),
    LuxtronikDataFieldDefinition(60, "ID_WEB_Zaehler_BetrZeitZWE1", Seconds),
    LuxtronikDataFieldDefinition(61, "ID_WEB_Zaehler_BetrZeitZWE2", Seconds),
    LuxtronikDataFieldDefinition(62, "ID_WEB_Zaehler_BetrZeitZWE3", Seconds),
    LuxtronikDataFieldDefinition(63, "ID_WEB_Zaehler_BetrZeitWP", Seconds),
    LuxtronikDataFieldDefinition(64, "ID_WEB_Zaehler_BetrZeitHz", Seconds),
    LuxtronikDataFieldDefinition(65, "ID_WEB_Zaehler_BetrZeitBW", Seconds),
    LuxtronikDataFieldDefinition(66, "ID_WEB_Zaehler_BetrZeitKue", Seconds),
    LuxtronikDataFieldDefinition(67, "ID_WEB_Time_WPein_akt", Seconds),
    LuxtronikDataFieldDefinition(68, "ID_WEB_Time_ZWE1_akt", Seconds),
    LuxtronikDataFieldDefinition(69, "ID_WEB_Time_ZWE2_akt", Seconds),
    LuxtronikDataFieldDefinition(70, "ID_WEB_Timer_EinschVerz", Seconds),
    LuxtronikDataFieldDefinition(71, "ID_WEB_Time_SSPAUS_akt", Seconds),
    LuxtronikDataFieldDefinition(72, "ID_WEB_Time_SSPEIN_akt", Seconds),
    LuxtronikDataFieldDefinition(73, "ID_WEB_Time_VDStd_akt", Seconds),
    LuxtronikDataFieldDefinition(74, "ID_WEB_Time_HRM_akt", Seconds),
    LuxtronikDataFieldDefinition(75, "ID_WEB_Time_HRW_akt", Seconds),
    LuxtronikDataFieldDefinition(76, "ID_WEB_Time_LGS_akt", Seconds),
    LuxtronikDataFieldDefinition(77, "ID_WEB_Time_SBW_akt", Seconds),
    LuxtronikDataFieldDefinition(78, "ID_WEB_Code_WP_akt", HeatpumpCode),
    LuxtronikDataFieldDefinition(79, "ID_WEB_BIV_Stufe_akt", BivalenceLevel),
    LuxtronikDataFieldDefinition(80, "ID_WEB_WP_BZ_akt", OperationMode),
    LuxtronikDataFieldDefinition(81, "ID_WEB_SoftStand", Version),
    LuxtronikDataFieldDefinition(82, "ID_WEB_SoftStand02", Unknown),
    LuxtronikDataFieldDefinition(83, "ID_WEB_SoftStand03", Unknown),
    LuxtronikDataFieldDefinition(84, "ID_WEB_SoftStand04", Unknown),
    LuxtronikDataFieldDefinition(85, "ID_WEB_SoftStand05", Unknown),
    LuxtronikDataFieldDefinition(86, "ID_WEB_SoftStand06", Unknown),
    LuxtronikDataFieldDefinition(87, "ID_WEB_SoftStand07", Unknown),
    LuxtronikDataFieldDefinition(88, "ID_WEB_SoftStand08", Unknown),
    LuxtronikDataFieldDefinition(89, "ID_WEB_SoftStand09", Unknown),
    LuxtronikDataFieldDefinition(90, "ID_WEB_SoftStand10", Unknown),
    LuxtronikDataFieldDefinition(91, "ID_WEB_AdresseIP_akt", IPAddress),
    LuxtronikDataFieldDefinition(92, "ID_WEB_SubNetMask_akt", IPAddress),
    LuxtronikDataFieldDefinition(93, "ID_WEB_Add_Broadcast", IPAddress),
    LuxtronikDataFieldDefinition(94, "ID_WEB_Add_StdGateway", IPAddress),
    LuxtronikDataFieldDefinition(95, "ID_WEB_ERROR_Time0", Timestamp),
    LuxtronikDataFieldDefinition(96, "ID_WEB_ERROR_Time1", Timestamp),
    LuxtronikDataFieldDefinition(97, "ID_WEB_ERROR_Time2", Timestamp),
    LuxtronikDataFieldDefinition(98, "ID_WEB_ERROR_Time3", Timestamp),
    LuxtronikDataFieldDefinition(99, "ID_WEB_ERROR_Time4", Timestamp),
    LuxtronikDataFieldDefinition(100, "ID_WEB_ERROR_Nr0", Errorcode),
    LuxtronikDataFieldDefinition(101, "ID_WEB_ERROR_Nr1", Errorcode),
    LuxtronikDataFieldDefinition(102, "ID_WEB_ERROR_Nr2", Errorcode),
    LuxtronikDataFieldDefinition(103, "ID_WEB_ERROR_Nr3", Errorcode),
    LuxtronikDataFieldDefinition(104, "ID_WEB_ERROR_Nr4", Errorcode),
    LuxtronikDataFieldDefinition(105, "ID_WEB_AnzahlFehlerInSpeicher", Count),
    LuxtronikDataFieldDefinition(106, "ID_WEB_Switchoff_file_Nr0", SwitchoffFile),
    LuxtronikDataFieldDefinition(107, "ID_WEB_Switchoff_file_Nr1", SwitchoffFile),
    LuxtronikDataFieldDefinition(108, "ID_WEB_Switchoff_file_Nr2", SwitchoffFile),
    LuxtronikDataFieldDefinition(109, "ID_WEB_Switchoff_file_Nr3", SwitchoffFile),
    LuxtronikDataFieldDefinition(110, "ID_WEB_Switchoff_file_Nr4", SwitchoffFile),
    LuxtronikDataFieldDefinition(111, "ID_WEB_Switchoff_file_Time0", Timestamp),
    LuxtronikDataFieldDefinition(112, "ID_WEB_Switchoff_file_Time1", Timestamp),
    LuxtronikDataFieldDefinition(113, "ID_WEB_Switchoff_file_Time2", Timestamp),
    LuxtronikDataFieldDefinition(114, "ID_WEB_Switchoff_file_Time3", Timestamp),
    LuxtronikDataFieldDefinition(115, "ID_WEB_Switchoff_file_Time4", Timestamp),
    LuxtronikDataFieldDefinition(116, "ID_WEB_Comfort_exists", Bool),
    LuxtronikDataFieldDefinition(117, "ID_WEB_HauptMenuStatus_Zeile1", MainMenuStatusLine1),
    LuxtronikDataFieldDefinition(118, "ID_WEB_HauptMenuStatus_Zeile2", MainMenuStatusLine2),
    LuxtronikDataFieldDefinition(119, "ID_WEB_HauptMenuStatus_Zeile3", MainMenuStatusLine3),
    LuxtronikDataFieldDefinition(120, "ID_WEB_HauptMenuStatus_Zeit", Seconds),
    LuxtronikDataFieldDefinition(121, "ID_WEB_HauptMenuAHP_Stufe", Level),
    LuxtronikDataFieldDefinition(122, "ID_WEB_HauptMenuAHP_Temp", Celsius),
    LuxtronikDataFieldDefinition(123, "ID_WEB_HauptMenuAHP_Zeit", Seconds),
    LuxtronikDataFieldDefinition(124, "ID_WEB_SH_BWW", Bool),
    LuxtronikDataFieldDefinition(125, "ID_WEB_SH_HZ", Icon),
    LuxtronikDataFieldDefinition(126, "ID_WEB_SH_MK1", Icon),
    LuxtronikDataFieldDefinition(127, "ID_WEB_SH_MK2", Icon),
    LuxtronikDataFieldDefinition(128, "ID_WEB_Einst_Kurzrpgramm", Unknown),
    LuxtronikDataFieldDefinition(129, "ID_WEB_StatusSlave_1", Unknown),
    LuxtronikDataFieldDefinition(130, "ID_WEB_StatusSlave_2", Unknown),
    LuxtronikDataFieldDefinition(131, "ID_WEB_StatusSlave_3", Unknown),
    LuxtronikDataFieldDefinition(132, "ID_WEB_StatusSlave_4", Unknown),
    LuxtronikDataFieldDefinition(133, "ID_WEB_StatusSlave_5", Unknown),
    LuxtronikDataFieldDefinition(134, "ID_WEB_AktuelleTimeStamp", Timestamp),
    LuxtronikDataFieldDefinition(135, "ID_WEB_SH_MK3", Icon),
    LuxtronikDataFieldDefinition(136, "ID_WEB_Sollwert_TVL_MK3", Celsius),
    LuxtronikDataFieldDefinition(137, "ID_WEB_Temperatur_TFB3", Celsius),
    LuxtronikDataFieldDefinition(138, "ID_WEB_MZ3out", Bool),
    LuxtronikDataFieldDefinition(139, "ID_WEB_MA3out", Bool),
    LuxtronikDataFieldDefinition(140, "ID_WEB_FP3out", Bool),
    LuxtronikDataFieldDefinition(141, "ID_WEB_Time_AbtIn", Seconds),
    LuxtronikDataFieldDefinition(142, "ID_WEB_Temperatur_RFV2", Celsius),
    LuxtronikDataFieldDefinition(143, "ID_WEB_Temperatur_RFV3", Celsius),
    LuxtronikDataFieldDefinition(144, "ID_WEB_SH_SW", Icon),
    LuxtronikDataFieldDefinition(145, "ID_WEB_Zaehler_BetrZeitSW", Unknown),
    LuxtronikDataFieldDefinition(146, "ID_WEB_FreigabKuehl", Bool),
    LuxtronikDataFieldDefinition(147, "ID_WEB_AnalogIn", Voltage),
    LuxtronikDataFieldDefinition(148, "ID_WEB_SonderZeichen", Unknown),
    LuxtronikDataFieldDefinition(149, "ID_WEB_SH_ZIP", Icon),
    LuxtronikDataFieldDefinition(150, "ID_WEB_WebsrvProgrammWerteBeobarten", Icon),
    LuxtronikDataFieldDefinition(151, "ID_WEB_WMZ_Heizung", Energy),
    LuxtronikDataFieldDefinition(152, "ID_WEB_WMZ_Brauchwasser", Energy),
    LuxtronikDataFieldDefinition(153, "ID_WEB_WMZ_Schwimmbad", Energy),
    LuxtronikDataFieldDefinition(154, "ID_WEB_WMZ_Seit", Energy),
    LuxtronikDataFieldDefinition(155, "ID_WEB_WMZ_Durchfluss", Flow),
    LuxtronikDataFieldDefinition(156, "ID_WEB_AnalogOut1", Voltage),
    LuxtronikDataFieldDefinition(157, "ID_WEB_AnalogOut2", Voltage),
    LuxtronikDataFieldDefinition(158, "ID_WEB_Time_Heissgas", Seconds),
    LuxtronikDataFieldDefinition(159, "ID_WEB_Temp_Lueftung_Zuluft", Celsius),
    LuxtronikDataFieldDefinition(160, "ID_WEB_Temp_Lueftung_Abluft", Celsius),
    LuxtronikDataFieldDefinition(161, "ID_WEB_Zaehler_BetrZeitSolar", Seconds),
    LuxtronikDataFieldDefinition(162, "ID_WEB_AnalogOut3", Voltage),
    LuxtronikDataFieldDefinition(163, "ID_WEB_AnalogOut4", Voltage),
    LuxtronikDataFieldDefinition(164, "ID_WEB_Out_VZU", Voltage),
    LuxtronikDataFieldDefinition(165, "ID_WEB_Out_VAB", Voltage),
    LuxtronikDataFieldDefinition(166, "ID_WEB_Out_VSK", Bool),
    LuxtronikDataFieldDefinition(167, "ID_WEB_Out_FRH", Bool),
    LuxtronikDataFieldDefinition(168, "ID_WEB_AnalogIn2", Voltage),
    LuxtronikDataFieldDefinition(169, "ID_WEB_AnalogIn3", Voltage),
    LuxtronikDataFieldDefinition(170, "ID_WEB_SAXin", Bool),
    LuxtronikDataFieldDefinition(171, "ID_WEB_SPLin", Bool),
    LuxtronikDataFieldDefinition(172, "ID_WEB_Compact_exists", Bool),
    LuxtronikDataFieldDefinition(173, "ID_WEB_Durchfluss_WQ", Flow),
    LuxtronikDataFieldDefinition(174, "ID_WEB_LIN_exists", Bool),
    LuxtronikDataFieldDefinition(175, "ID_WEB_LIN_ANSAUG_VERDAMPFER", Celsius),
    LuxtronikDataFieldDefinition(176, "ID_WEB_LIN_ANSAUG_VERDICHTER", Celsius),
    LuxtronikDataFieldDefinition(177, "ID_WEB_LIN_VDH", Celsius),
    LuxtronikDataFieldDefinition(178, "ID_WEB_LIN_UH", Kelvin),
    LuxtronikDataFieldDefinition(179, "ID_WEB_LIN_UH_Soll", Kelvin),
    LuxtronikDataFieldDefinition(180, "ID_WEB_LIN_HD", Pressure),
    LuxtronikDataFieldDefinition(181, "ID_WEB_LIN_ND", Pressure),
    LuxtronikDataFieldDefinition(182, "ID_WEB_LIN_VDH_out", Bool),
    LuxtronikDataFieldDefinition(183, "ID_WEB_HZIO_PWM", Percent2),
    LuxtronikDataFieldDefinition(184, "ID_WEB_HZIO_VEN", Speed),
    LuxtronikDataFieldDefinition(185, "ID_WEB_HZIO_EVU2", Unknown),
    LuxtronikDataFieldDefinition(186, "ID_WEB_HZIO_STB", Bool),
    LuxtronikDataFieldDefinition(187, "ID_WEB_SEC_Qh_Soll", Energy),
    LuxtronikDataFieldDefinition(188, "ID_WEB_SEC_Qh_Ist", Energy),
    LuxtronikDataFieldDefinition(189, "ID_WEB_SEC_TVL_Soll", Celsius),
    LuxtronikDataFieldDefinition(190, "ID_WEB_SEC_Software", Unknown),
    LuxtronikDataFieldDefinition(191, "ID_WEB_SEC_BZ", SecOperationMode),
    LuxtronikDataFieldDefinition(192, "ID_WEB_SEC_VWV", Unknown),
    LuxtronikDataFieldDefinition(193, "ID_WEB_SEC_VD", Speed),
    LuxtronikDataFieldDefinition(194, "ID_WEB_SEC_VerdEVI", Celsius),
    LuxtronikDataFieldDefinition(195, "ID_WEB_SEC_AnsEVI", Celsius),
    LuxtronikDataFieldDefinition(196, "ID_WEB_SEC_UEH_EVI", Kelvin),
    LuxtronikDataFieldDefinition(197, "ID_WEB_SEC_UEH_EVI_S", Kelvin),
    LuxtronikDataFieldDefinition(198, "ID_WEB_SEC_KondTemp", Celsius),
    LuxtronikDataFieldDefinition(199, "ID_WEB_SEC_FlussigEx", Celsius),
    LuxtronikDataFieldDefinition(200, "ID_WEB_SEC_UK_EEV", Celsius),
    LuxtronikDataFieldDefinition(201, "ID_WEB_SEC_EVI_Druck", Pressure),
    LuxtronikDataFieldDefinition(202, "ID_WEB_SEC_U_Inv", Voltage),
    LuxtronikDataFieldDefinition(203, "ID_WEB_Temperatur_THG_2", Celsius),
    LuxtronikDataFieldDefinition(204, "ID_WEB_Temperatur_TWE_2", Celsius),
    LuxtronikDataFieldDefinition(205, "ID_WEB_LIN_ANSAUG_VERDAMPFER_2", Celsius),
    LuxtronikDataFieldDefinition(206, "ID_WEB_LIN_ANSAUG_VERDICHTER_2", Celsius),
    LuxtronikDataFieldDefinition(207, "ID_WEB_LIN_VDH_2", Celsius),
    LuxtronikDataFieldDefinition(208, "ID_WEB_LIN_UH_2", Kelvin),
    LuxtronikDataFieldDefinition(209, "ID_WEB_LIN_UH_Soll_2", Kelvin),
    LuxtronikDataFieldDefinition(210, "ID_WEB_LIN_HD_2", Pressure),
    LuxtronikDataFieldDefinition(211, "ID_WEB_LIN_ND_2", Pressure),
    LuxtronikDataFieldDefinition(212, "ID_WEB_HDin_2", Bool),
    LuxtronikDataFieldDefinition(213, "ID_WEB_AVout_2", Bool),
    LuxtronikDataFieldDefinition(214, "ID_WEB_VBOout_2", Bool),
    LuxtronikDataFieldDefinition(215, "ID_WEB_VD1out_2", Bool),
    LuxtronikDataFieldDefinition(216, "ID_WEB_LIN_VDH_out_2", Bool),
    LuxtronikDataFieldDefinition(217, "ID_WEB_Switchoff2_file_Nr0", SwitchoffFile),
    LuxtronikDataFieldDefinition(218, "ID_WEB_Switchoff2_file_Nr1", SwitchoffFile),
    LuxtronikDataFieldDefinition(219, "ID_WEB_Switchoff2_file_Nr2", SwitchoffFile),
    LuxtronikDataFieldDefinition(220, "ID_WEB_Switchoff2_file_Nr3", SwitchoffFile),
    LuxtronikDataFieldDefinition(221, "ID_WEB_Switchoff2_file_Nr4", SwitchoffFile),
    LuxtronikDataFieldDefinition(222, "ID_WEB_Switchoff2_file_Time0", Timestamp),
    LuxtronikDataFieldDefinition(223, "ID_WEB_Switchoff2_file_Time1", Timestamp),
    LuxtronikDataFieldDefinition(224, "ID_WEB_Switchoff2_file_Time2", Timestamp),
    LuxtronikDataFieldDefinition(225, "ID_WEB_Switchoff2_file_Time3", Timestamp),
    LuxtronikDataFieldDefinition(226, "ID_WEB_Switchoff2_file_Time4", Timestamp),
    LuxtronikDataFieldDefinition(227, "ID_WEB_RBE_RT_Ist", Celsius),
    LuxtronikDataFieldDefinition(228, "ID_WEB_RBE_RT_Soll", Celsius),
    LuxtronikDataFieldDefinition(229, "ID_WEB_Temperatur_BW_oben", Celsius),
    LuxtronikDataFieldDefinition(230, "ID_WEB_Code_WP_akt_2", HeatpumpCode),
    LuxtronikDataFieldDefinition(231, "ID_WEB_Freq_VD", Frequency),
    LuxtronikDataFieldDefinition(232, "Unknown_Calculation_232", Unknown),
    LuxtronikDataFieldDefinition(233, "Unknown_Calculation_233", Unknown),
    LuxtronikDataFieldDefinition(234, "Unknown_Calculation_234", Unknown),
    LuxtronikDataFieldDefinition(235, "Unknown_Calculation_235", Unknown),
    LuxtronikDataFieldDefinition(236, "Unknown_Calculation_236", Unknown),
    LuxtronikDataFieldDefinition(237, "Unknown_Calculation_237", Unknown),
    LuxtronikDataFieldDefinition(238, "Unknown_Calculation_238", Unknown),
    LuxtronikDataFieldDefinition(239, "Unknown_Calculation_239", Unknown),
    LuxtronikDataFieldDefinition(240, "Unknown_Calculation_240", Unknown),
    LuxtronikDataFieldDefinition(241, "Circulation_Pump", Percent2),
    LuxtronikDataFieldDefinition(242, "Unknown_Calculation_242", Unknown),
    LuxtronikDataFieldDefinition(243, "Unknown_Calculation_243", Unknown),
    LuxtronikDataFieldDefinition(244, "Unknown_Calculation_244", Unknown),
    LuxtronikDataFieldDefinition(245, "Unknown_Calculation_245", Unknown),
    LuxtronikDataFieldDefinition(246, "Unknown_Calculation_246", Unknown),
    LuxtronikDataFieldDefinition(247, "Unknown_Calculation_247", Unknown),
    LuxtronikDataFieldDefinition(248, "Unknown_Calculation_248", Unknown),
    LuxtronikDataFieldDefinition(249, "Unknown_Calculation_249", Unknown),
    LuxtronikDataFieldDefinition(250, "Unknown_Calculation_250", Unknown),
    LuxtronikDataFieldDefinition(251, "Unknown_Calculation_251", Unknown),
    LuxtronikDataFieldDefinition(252, "Unknown_Calculation_252", Unknown),
    LuxtronikDataFieldDefinition(253, "Unknown_Calculation_253", Unknown),
    LuxtronikDataFieldDefinition(254, "Flow_Rate_254", Flow),
    LuxtronikDataFieldDefinition(255, "Unknown_Calculation_255", Unknown),
    LuxtronikDataFieldDefinition(256, "Unknown_Calculation_256", Unknown),
    LuxtronikDataFieldDefinition(257, "Heat_Output", Power),
    LuxtronikDataFieldDefinition(258, "Unknown_Calculation_258", Unknown),
    LuxtronikDataFieldDefinition(259, "Unknown_Calculation_259", Unknown),
]
# fmt: on


class CalculationFactory(LuxtronikDataFieldFactory):
    """Factory to look-up calculation definitions or to create calculations."""

    _data_field_defs = CALCULATION_DEFINITIONS


class Calculations(LuxtronikDataFieldDict):
    """Class that holds all calculations."""

    def __init__(self):
        """Initialize calculation dict."""
        super().__init__("Calculation", CalculationFactory)

    def _extract_data(self, index, raw_data):
        # index is version info, parse entire range from 81 up to 90 as version string
        if index == 81:
            return 91, raw_data[81:90]
        return super()._extract_data(index, raw_data)
